name       : unison
version    : 2.48.4
release    : 2
source     :
    - http://www.seas.upenn.edu/~bcpierce/unison//download/releases/stable/unison-2.48.4.tar.gz : 30aa53cd671d673580104f04be3cf81ac1e20a2e8baaf7274498739d59e99de8
license    : GPL-3.0
component  : network.util
summary    : Unison is a file-synchronization tool for Unix and Windows.
description: |
    Unison is a file-synchronization tool for Unix and Windows. It allows two replicas of a collection of files and directories to be stored on different hosts (or different disks on the same host), modified separately, and then brought up to date by propagating the changes in each replica to the other.
builddeps  :
    - ocaml
build      : |
    CFLAGS=""
    make -j1
install    : |
    install -d $installdir/usr/bin/
    install -m 00755 unison $installdir/usr/bin/unison
    install -m 00755 unison-fsmonitor $installdir/usr/bin/unison-fsmonitor
